### ISSUE TITLE
Revision 4 issues

### ISSUE THREAD

**Issue by Zambiorix** [AprilBrother/esp-flasher#2]
Hi,

I bought a few of these:
https://wiki.aprbrother.com/en/ESP_Flasher_Rev4.html

I bought it from Aliexpress:
https://www.aliexpress.com/item/ESP8266-Flasher-Rev2/32556128986.html?spm=a2g0s.9042311.0.0.3da24c4dcvURay

... is that from you? or is this a copycat?

Is the schematic changed much between rev 3 and rev 4?

I had to connect the programmer to a ESP32-WROOM-32U device, following the link above (swapping TXD and RXD), but that didn't work...

I had to connect TXD to TXD and RXD to RXD.

I also found out that the silkscreen on the backside, TXD and RXD are different than mentioned in the link above...

I am just wondering if I bought from a copycat and they made an error in the layout/silkscreen ...

Thanks!

**Comment by volca** [comment]
It's our store at Aliexpress. You can found the schematic at the bottom of [the wiki](https://wiki.aprbrother.com/en/ESP_Flasher_Rev4.html). 

For programming ESP32 module, you need remove a little resistor from the board. It's also compatible with previousPSE8266 module if you removed the resistor.

See the red circle in the photo

![esp-flasher-red](https://user-images.githubusercontent.com/196212/50670182-c9056b80-1004-11e9-885d-af5b0f2ee485.png)

**Comment by volca** [comment]
Thanks for your good news!

The label on the front is for compatible with our another board [ESPea](https://wiki.aprbrother.com/en/ESPea.html). I'm sorry it made you confuse

**Comment by Zambiorix** [comment]
ok, thanks!
